<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-2K7UCEJ" failures="1" tests="1" name="ZoomInfo.ChatBotTesting.TestRunner" time="23.174" errors="0" timestamp="2023-03-22T17:34:59 IST" skipped="0">
  <testcase classname="ZoomInfo.ChatBotTesting.TestRunner" name="runScenario" time="23.174">
    <failure message="expected [jnj] but found [Welcome to ZoomInfo Chat!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [jnj] but found [Welcome to ZoomInfo Chat!]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at ZoomInfo.ChatBotTesting.StepDefinitionChatBox.chat_bot_is_opened(StepDefinitionChatBox.java:25)
at âœ½.Chat bot is available(file:///C:/Users/Raj/Documents/AutomationProject/ZI/ChatBotTesting/src/test/java/ZoomInfo/ChatBotTesting/ChatBot.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- ZoomInfo.ChatBotTesting.TestRunner -->
